name: fastpythongpu311
channels:
  - conda-forge
dependencies:
  - python=3.11
  - jupyterlab
  - numpy
  - scipy
  - iminuit
  - tensorflow>=2.2
  - jax
  - matplotlib
  - pytorch
  - numba
  - pip
  - ipython
  - cuda-nvcc
  - cupy
